# SPDX-License-Identifier: GPL-3.0-or-later

from typing import Any, Self

class _Dynamic:
    def __getattr__(self, name: str) -> Any: ...

class Widget(_Dynamic): ...

class Button(Widget):
    @classmethod
    def new_with_label(cls, label: str) -> Self: ...

class ComboBoxText(Widget): ...

class MenuItem(Widget):
    @classmethod
    def new_with_label(cls, label: str) -> Self: ...
    @classmethod
    def new_with_mnemonic(cls, label: str) -> Self: ...

class ApplicationWindow(Widget): ...
class MenuBar(Widget): ...

def __getattr__(name: str) -> Any: ...
