# SPDX-License-Identifier: GPL-3.0-or-later

from typing import Any

class Widget: ...
class Button(Widget): ...
class ComboBoxText(Widget): ...
class MenuItem(Widget): ...
class ApplicationWindow(Widget): ...
class MenuBar(Widget): ...

def __getattr__(name: str) -> Any: ...
