// SPDX-License-Identifier: GPL-3.0-or-later
#include "affs_native.h"
#include "version.h"
#include <errno.h>
#include <fcntl.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#define PROG "linux-defragger-affs-worker"
static void usage(FILE *f){fprintf(f,"Usage: %s --version | identify DEVICE | analyse-json DEVICE | defrag|growth-defrag|recover DEVICE --write --confirm DEVICE --journal PATH [--growth-percent 10] [--live-updates]\n",PROG);}
static void result(const char *op,const char *st,const char *msg){printf("@@RESULT {\"operation\":\"%s\",\"status\":\"%s\",\"message\":\"%s\"}\n",op,st,msg?msg:"");fflush(stdout);}
static char *stage_name(const char *journal){size_t n=strlen(journal)+12;char *p=malloc(n);if(p)snprintf(p,n,"%s.affs-stage",journal);return p;}
static int save_journal(const char *j,const char *dev,const char *stage,const char *op){FILE *f=fopen(j,"w");if(!f)return -1;fprintf(f,"LINUX-DEFRAGGER-AFFS-1\ndevice=%s\nstage=%s\noperation=%s\n",dev,stage,op);if(fflush(f)||fsync(fileno(f))||fclose(f))return -1;return 0;}
static int load_journal(const char *j,char **dev,char **stage,char op[32]){FILE *f=fopen(j,"r");if(!f)return -1;char line[4096];if(!fgets(line,sizeof line,f)||strncmp(line,"LINUX-DEFRAGGER-AFFS-1",23)){fclose(f);return -1;}while(fgets(line,sizeof line,f)){line[strcspn(line,"\r\n")]=0;if(!strncmp(line,"device=",7))*dev=strdup(line+7);else if(!strncmp(line,"stage=",6))*stage=strdup(line+6);else if(!strncmp(line,"operation=",10))snprintf(op,32,"%.31s",line+10);}fclose(f);return *dev&&*stage&&op[0]?0:-1;}
int main(int argc,char **argv){if(argc==2&&!strcmp(argv[1],"--version")){puts(LD_VERSION);return 0;}if(argc<3){usage(stderr);return 2;}const char *mode=argv[1],*dev=argv[2];char *err=NULL;if(!strcmp(mode,"identify")){AffsVolume v;if(affs_scan(dev,false,&v,&err)){free(err);return 1;}printf("{\"filesystem\":\"affs\",\"variant\":\"%s\",\"dostype\":%u}\n",v.ffs?"FFS":"OFS",v.dostype);affs_close(&v);return 0;}if(!strcmp(mode,"analyse-json")){int r=affs_analyse_json(dev,&err);if(r){fprintf(stderr,"%s\n",err?err:"Amiga analysis failed");free(err);return 1;}return 0;}bool growth=!strcmp(mode,"growth-defrag"),defrag=!strcmp(mode,"defrag"),recover=!strcmp(mode,"recover");if(!growth&&!defrag&&!recover){usage(stderr);return 2;}const char *confirm=NULL,*journal=NULL;unsigned gp=10;bool write=false,live=false;for(int i=3;i<argc;i++){if(!strcmp(argv[i],"--write"))write=true;else if(!strcmp(argv[i],"--live-updates"))live=true;else if(!strcmp(argv[i],"--confirm")&&i+1<argc)confirm=argv[++i];else if(!strcmp(argv[i],"--journal")&&i+1<argc)journal=argv[++i];else if(!strcmp(argv[i],"--growth-percent")&&i+1<argc)gp=(unsigned)strtoul(argv[++i],NULL,10);else if((!strcmp(argv[i],"--workers")||!strcmp(argv[i],"--ram-buffer")||!strcmp(argv[i],"--batch-clusters")||!strcmp(argv[i],"--live-map-cells"))&&i+1<argc)i++;}
 if(!write||!journal||!confirm||strcmp(confirm,dev)){fprintf(stderr,"Amiga mutation requires --write --confirm DEVICE --journal PATH\n");return 2;}if(growth&&gp!=10){fprintf(stderr,"Amiga Growth Defrag requires exactly 10 percent reserve\n");return 2;}char *stage=NULL,*jdev=NULL;char jop[32]={0};if(recover){if(load_journal(journal,&jdev,&stage,jop)){fprintf(stderr,"Amiga recovery journal is missing or malformed\n");return 1;}if(strcmp(jdev,dev)){fprintf(stderr,"Amiga recovery journal target mismatch\n");free(jdev);free(stage);return 1;}uint64_t w=0;if(affs_verify_layout(stage,!strcmp(jop,"growth-defrag"),10,&err)||affs_commit_stage(stage,dev,&w,&err)||affs_verify_layout(dev,!strcmp(jop,"growth-defrag"),10,&err)){fprintf(stderr,"%s\n",err?err:"Amiga recovery failed");free(err);free(jdev);free(stage);return 1;}unlink(stage);unlink(journal);printf("Recovered verified Amiga source; committed %" PRIu64 " KiB of allocated blocks.\n", w / 1024U);result("recover","completed","");free(jdev);free(stage);return 0;}
 stage=stage_name(journal);if(!stage){fprintf(stderr,"out of memory\n");return 1;}printf("Starting native C Amiga %s on %s.\n",growth?"Growth Defrag":"Defrag",dev);uint64_t planned=0;if(affs_build_stage(dev,stage,growth,gp,live,&planned,&err)||affs_verify_layout(stage,growth,gp,&err)){fprintf(stderr,"%s\n",err?err:"Amiga stage failed");free(err);unlink(stage);free(stage);return 1;}if(save_journal(journal,dev,stage,mode)){fprintf(stderr,"cannot persist Amiga recovery journal: %s\n",strerror(errno));unlink(stage);free(stage);return 1;}printf("Amiga source commit: writing %" PRIu64 " KiB of verified allocated blocks only.\n", planned / 1024U);uint64_t written=0;if(affs_commit_stage(stage,dev,&written,&err)||affs_verify_layout(dev,growth,gp,&err)){fprintf(stderr,"%s\n",err?err:"Amiga source commit failed");free(err);free(stage);return 1;}unlink(stage);unlink(journal);if(live){printf("@@LIVE_RESET {\"reason\":\"authoritative post-commit Amiga map\"}\n");fflush(stdout);}printf("Amiga %s completed; committed %" PRIu64 " KiB of allocated blocks.\n", growth?"Growth Defrag":"Defrag", written / 1024U);result(mode,"completed","");free(stage);return 0;}
