#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
# Linux Defragger
# Author: Shannon Smith
# Purpose: Launch the installed GTK application without writing Python bytecode.

export PYTHONDONTWRITEBYTECODE=1

exec /usr/bin/python3 /usr/lib/linux-defragger/linux_defragger_gui.py "$@"
